### ISSUE TITLE
你的nuget还是哪有病毒吗？惠订房 - API文档是什么鬼？

### ISSUE THREAD

**Issue by wang2650** [li-keli/AspnetCoreApiDoc#2]
http://localhost:26293/core/v1/api.do打开后title变了。一闪而过。
查看网页的源码 里面是 <title>惠订房 - API文档</title>

这是什么鬼啊？

**Comment by li-keli** [comment]
哈，这个项目是从真实的业务代码里面抽离出来的，title可能当时没有剥离干净，我等会儿删除一下。

你是遇到什么问题了？/core/v1/api.do 打不开吗？

**Comment by li-keli** [comment]
若是有其他问题，请新开issues或者重新打开此issues。
我先关闭了
